"""Render a Vagrantfile from a ClusterConfig."""
import os
import shutil
import stat
import subprocess
from pathlib import Path
from config import ClusterConfig, NodeSpec

_THIS_DIR = Path(__file__).resolve().parent
_PROVISION_SRC = _THIS_DIR / "provision"

_VDISKMANAGER_CANDIDATES = [
    "/Applications/VMware Fusion.app/Contents/Library/vmware-vdiskmanager",
    "/Applications/VMware Fusion.app/Contents/Public/vmware-vdiskmanager",
]


VAGRANTFILE_HEADER = '''# -*- mode: ruby -*-
# Auto-generated by vmware-fusion-automation. DO NOT EDIT BY HAND.
Vagrant.configure("2") do |config|
  config.vm.box = "{box}"
  config.vm.synced_folder ".", "/vagrant", disabled: true
'''

NODE_TEMPLATE = '''
  config.vm.define "{name}" do |node|
    node.vm.hostname = "{name}"
    node.vm.network "private_network", ip: "{ip}"
    node.vm.provider "vmware_desktop" do |v|
      v.gui            = false
      v.linked_clone   = false
      v.memory         = {memory_mb}
      v.cpus           = {cpus}
      v.vmx["memsize"]           = "{memory_mb}"
      v.vmx["numvcpus"]          = "{cpus}"
      v.vmx["nvme0.present"]     = "TRUE"
{disk_lines}
    end
    node.vm.provision "shell", path: "provision/disk_setup.sh"
    node.vm.provision "shell", path: "provision/rackdc.sh", env: {{
      "DC_NAME" => "{dc_name}",
      "NODE_AZ" => "{az}"
    }}
    node.vm.provision "shell", path: "provision/setup_scylla.sh", env: {{
      "SCYLLA_VERSION" => "{scylla_version}",
      "MY_IP"          => "{ip}",
      "SEED_IP"        => "{seed_ip}",
      "CLUSTER_NAME"   => "{cluster_name}",
      "IS_SEED"        => "{is_seed}",
      "DC_NAME"        => "{dc_name}",
      "NODE_AZ"        => "{az}"
    }}
  end
'''

VAGRANTFILE_FOOTER = "end\n"


def _vmdk_path(target_folder: Path, node: NodeSpec, i: int) -> Path:
    return target_folder / "disks" / f"{node.name}-data{i}.vmdk"


def _disk_lines(node: NodeSpec, target_folder: Path) -> str:
    """vmx keys attaching pre-created VMDKs via the NVMe controller.
    We avoid Vagrant's config.vm.disk API because vagrant-vmware-desktop
    3.0.5 crashes on the arm64 bento box's SATA entry (disk.rb:129)."""
    lines = []
    for i in range(node.data.disk_count):
        path = _vmdk_path(target_folder, node, i)
        lines.append(f'      v.vmx["nvme0:{i}.present"]   = "TRUE"')
        lines.append(f'      v.vmx["nvme0:{i}.fileName"]  = "{path}"')
    return "\n".join(lines)


def _find_vdiskmanager() -> str:
    for path in _VDISKMANAGER_CANDIDATES:
        if Path(path).exists():
            return path
    raise FileNotFoundError(
        "vmware-vdiskmanager not found. Expected inside the VMware Fusion app bundle."
    )


def _create_vmdks(config: ClusterConfig) -> None:
    """Pre-create one sparse VMDK per data disk per node."""
    vdisk = _find_vdiskmanager()
    disks_dir = Path(config.target_folder) / "disks"
    disks_dir.mkdir(parents=True, exist_ok=True)
    for node in config.nodes:
        for i in range(node.data.disk_count):
            path = _vmdk_path(Path(config.target_folder), node, i)
            if path.exists():
                continue
            cmd = [
                vdisk, "-c",
                "-s", f"{node.data.size_gb}GB",
                "-a", "lsilogic",
                "-t", "0",             # growable monolithic sparse
                str(path),
            ]
            print(f"$ {' '.join(cmd)}", flush=True)
            subprocess.run(cmd, check=True)


def render(config: ClusterConfig) -> str:
    target_folder = Path(config.target_folder).resolve()
    parts = [VAGRANTFILE_HEADER.format(box=config.box_name)]
    for idx, node in enumerate(config.nodes):
        parts.append(NODE_TEMPLATE.format(
            name=node.name,
            ip=node.ip,
            memory_mb=config.memory_mb,
            cpus=config.cpus,
            disk_lines=_disk_lines(node, target_folder),
            dc_name=node.dc,
            az=node.az,
            scylla_version=config.scylla_version,
            seed_ip=config.seed_ip,
            cluster_name=config.cluster_name,
            is_seed="1" if node.ip == config.seed_ip else "0",
        ))
    parts.append(VAGRANTFILE_FOOTER)
    return "".join(parts)


def _copy_provision_scripts(target_folder: Path) -> None:
    """Copy provision/*.sh next to the generated Vagrantfile so that the
    relative `path` references in the Vagrantfile resolve correctly."""
    dest = target_folder / "provision"
    dest.mkdir(parents=True, exist_ok=True)
    for src in _PROVISION_SRC.glob("*.sh"):
        dst = dest / src.name
        shutil.copy2(src, dst)
        dst.chmod(dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def write_vagrantfile(config: ClusterConfig, create_disks: bool = True) -> str:
    folder = Path(config.target_folder)
    folder.mkdir(parents=True, exist_ok=True)
    target = folder / "Vagrantfile"
    target.write_text(render(config))
    _copy_provision_scripts(folder)
    if create_disks:
        _create_vmdks(config)
    return str(target)
